<h1 class="text-center">Connect</h1>

<form class="" role="form" action="<?= $this->url('connect') ?>" method="post">

<div class="form-group">
        <label class="col-sm-1 control-label" for="email">Email</label>
        <div class="col-sm-11">
            <input class="form-control" type="email" name="email" id="email" placeholder="Enter your email here">
        </div>
</div>
    

<div class="form-group">
        <label class="col-sm-1 control-label" for="password">Password</label>
        <div class="col-sm-11">
            <input class="form-control" type="password" name="password" id="password" placeholder="Enter your password here">
        </div>
</div>
<div class="text-center form-group">
    <button type="submit" class="btn btn-success">Connect</button>
</div>

</form>