<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="btn btn-success" href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">


<?php foreach ($albums as $album) : ?>
<div class="col-sm-3">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://picsum.photos/200/300" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><?= $this->escapeHtml($album->title) ?></h5>
    <p class="card-text"><?= $this->escapeHtml($album->artist) ?></p>
    <a href="#" class="btn btn-primary">Ajout panier</a>
  </div>
  
            <a class="btn btn-warning" href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <a class="btn btn-danger" href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
</div>        
</div>
<?php endforeach; ?>
</table>