<?php
$title = 'Register';
$this->headTitle($title);
?>

<h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>

<form class="" role="form" action="<?= $this->url('register') ?>" method="post">

<div class="form-group">
        <label style="margin-top: 25px;" class="col-sm-1 control-label" for="username">Username</label>
        <div class="col-sm-11">
            <input style="margin-top: 25px;" class="form-control" type="username" name="username" id="username" placeholder="Enter your username here">
        </div>
</div>
    
<div class="form-group">
        <label style="margin-top: 25px;" class="col-sm-1 control-label" for="email">Email</label>
        <div class="col-sm-11">
            <input style="margin-top: 25px;" class="form-control" type="email" name="email" id="email" placeholder="Enter your email here">
        </div>
</div>
    
<div class="form-group">
        <label style="margin-top: 25px;" class="col-sm-1 control-label" for="password">Password</label>
        <div class="col-sm-11">
            <input style="margin-top: 25px;" class="form-control" type="password" name="password" id="password" placeholder="Enter your password here">
        </div>
</div>
<div class="text-center form-group">
    <button style="margin-top: 50px;" type="submit" class="btn btn-success">Register</button>
</div>

</form>
