<?php
$title = 'Register';
$this->headTitle($title);
?>
<h1 class="text-center"><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
    $username = $form->get('username');
    $username->setAttribute('class', 'form-control');
    $username->setAttribute('placeholder', 'Username');
    
    $email = $form->get('email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('placeholder', 'Email');
    
    $password = $form->get('password');
    $password->setAttribute('class', 'form-control');
    $password->setAttribute('placeholder', 'Password');
    
    $permission = $form->get('permission');
    $permission->setAttribute('class', 'form-control');
    $permission->setAttribute('placeholder', 'Permission');
    
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-success');

    $form->setAttribute('action', $this->url('users', [
        'action' => 'register',
        'id'     => $id,
    ]));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>

    <div class="form-group">
        <?= $this->formLabel($username) ?>
        <?= $this->formElement($username) ?>
        <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
        <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
    </div>
    
        <div class="text-center">
            <?php
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>